# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-08-17 21:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParameterPencairan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_bank', models.CharField(blank=True, choices=[('', '---PILIH---'), ('9', 'Bank Syariah Bukopin'), ('8', 'Bank Bukopin')], max_length=2)),
                ('status_pensiun', models.CharField(blank=True, choices=[('', '--PILIH--'), ('1', 'Sendiri'), ('2', 'Janda'), ('3', 'Duda Sendiri'), ('4', 'Duda Turunan')], max_length=2, null=True)),
                ('max_usia', models.IntegerField(blank=True, null=True)),
                ('min_usia', models.IntegerField(blank=True, null=True)),
                ('max_plafon', models.FloatField(null=True)),
                ('min_plafon', models.FloatField(null=True)),
                ('max_tenor', models.IntegerField(null=True)),
                ('min_tenor', models.IntegerField(null=True)),
                ('max_tiring_tenor', models.IntegerField(blank=True, null=True)),
                ('min_tiring_tenor', models.IntegerField(blank=True, null=True)),
                ('rete_produk', models.FloatField(null=True)),
                ('jenis_bunga', models.CharField(blank=True, choices=[('0', '--PILIH--'), ('1', 'FLAT'), ('2', 'ANUITAS'), ('3', 'EFEKTIF')], max_length=10, null=True)),
                ('adm', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('provisi', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('bunga', models.DecimalField(blank=True, decimal_places=4, default=0, help_text='Bunga Pertahun Tetapi Sudah Di bagi 100 ch jika 24% Pertahun maka input 0,24', max_digits=12, null=True)),
                ('dsr', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('jenis_pengajuan', models.CharField(blank=True, choices=[('1', 'SKEP ON HAND'), ('2', 'TAKE OVER')], max_length=2, null=True)),
                ('kantor_bayar', models.CharField(blank=True, choices=[('', '--PILIH--'), ('1', 'Kantor Pos'), ('2', 'Bank BSB'), ('3', 'Bank Bukopin')], max_length=2, null=True)),
                ('status', models.CharField(blank=True, choices=[('1', 'Aktif'), ('2', 'None Aktif')], max_length=50, null=True)),
                ('tanggal', models.DateField(blank=True, null=True)),
                ('max_bulan_usia', models.IntegerField(blank=True, null=True)),
                ('max_hari_usia', models.IntegerField(blank=True, null=True)),
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('mdate', models.DateTimeField(auto_now=True)),
                ('bunga_bank', models.DecimalField(blank=True, decimal_places=4, default=0, help_text='Bunga Pertahun Tetapi Sudah Di bagi 100 ch jika 24% Pertahun maka input 0,24', max_digits=12, null=True)),
                ('cu', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('mu', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'parameterpencairan',
                'verbose_name': 'ParameterPencairan',
                'verbose_name_plural': 'ParameterPencairan',
            },
        ),
        migrations.CreateModel(
            name='Produk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_prod', models.IntegerField(null=True)),
                ('nama_produk', models.CharField(max_length=100, null=True)),
                ('tgl_aktif', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('1', 'AKTIF'), ('2', 'NONAKTIF')], max_length=4)),
            ],
            options={
                'db_table': 'produk',
                'verbose_name': 'Produk',
                'verbose_name_plural': 'Produk',
            },
        ),
        migrations.AddField(
            model_name='parameterpencairan',
            name='produk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='paramkredit.Produk'),
        ),
    ]
